### ISSUE TITLE
Vertaisarviointi 28.9.2023

### ISSUE THREAD

**Issue by fialco** [jmakine/Koe-sovellus#1]
# Dokumentaatio
* Readme selkeä ja ohjelman käyttöönotto-ohjeet toimivat 
* TODO listalla hyviä asioita

# Ohjelma ja sen käyttö
## Hyvää
* Ohjelma toimintakunnossa ja hyvässä vaiheessa
* Ohjelmaa helppo käyttää ja ulkonäkö on siisti
* Koe/käyttäjätilastot näyttäisi pitävän paikkaansa
## Huomioita
* Jos kysymyksiä ei ole tai kaikki kysymykset ovat jo kokeessa pystyy yrittää lähettää "tyhjän" kysymyksen joka aiheuttaa Bad requestin
* Kysymyksen lisäämisen yhteydessä tuleva huomio että lisääminen vaikuttaa suoritettuihin kokeisiin on hieman liikaa jokaisen lisäyksen kohdalla
  * Varsinkin jos lisättäviä kysymyksiä on paljon
* Jos opettajia on yksi ja yrität poistaa  oppilaita tulee ilmoitus "Et voi poistaa ainutta opettajaa"
* Oppilaana pystyy kirjoittamaan selaimen hakuun esim "http://127.0.0.1:5000/users_table" ja "http://127.0.0.1:5000/subjects" ja pääsee tarkastelemaan sisältöä

# Koodi ja tietokanta
## Hyvää
* Tietokantoja sopiva määrä ja käsittelevät selkeitä kokonaisuuksia
* Koodia hajautettu sopiviin tiedostoihin ja funktioihin
* Funktioiden nimistä pystyy suurin piirtein päättelemään mitä niissä tapahtuu
* SQL hakuja käytetty todella monipuolisesti

## Huomioita
* Ainakin subjects.py sisältää "SELECT *" SQL hakuja joita ei suositella kurssin teknisellä tarkistuslistalla
* Lomakkeista kuten käyttäjän rekisteröinti puuttuu CSRF tarkastus

**Comment by jmakine** [comment]
Loistavia huomioita, kiitos paljon! :)
Kaikki korjattu.
