### ISSUE TITLE
Välipalautus 3: vertaisarviointi

### ISSUE THREAD

**Issue by villesalmela** [jmakine/Koe-sovellus#2]
# Välipalautus 3: vertaisarviointi
## Lyhyesti
Sovellus on hyvässä vaiheessa ja siinä ei ole suuria haasteita. Palautteessa keskityn kehumaan kokonaisuutta ja nostamaan yksittäisiä kehityskohteita esille.

### Tietokanta
Tietokantaskeema on selkeä, hyvin valittuine datatyyppeineen, tarkistuksineen ja viittauksineen.
Tietokantakomennot ovat verrattain monimutkaisia, formatoitu mukavan luettaviksi ja käyttökokemuksen perusteella ilmeisen toimivia.

### Käyttökokemus
Sovelluksen logiikka tuntuu helposti ymmärrettävältä ja toimivalta, operointi on intuitiivista.
Ulkoasu on siisti ja asiallinen, oikein sopiva. Käyttöliittymän tehostevärit "vaarallisissa" napeissa tukee selkeyttä.

### Koodi
Muuttujat ja funktiot on järkevästi nimetty, niin koodia on helppo lukea. Tässä on myös jo ihan kunnon kasa koodia, mutta silti kaikella vaikuttaa olevan selkeästi oma paikkansa ja roolinsa, mikä on mun mielestä jäsentelyn saralla hyvä saavutus.

## Kehitettävää
Vaikka olenkin alle koonnut havaintoja eräänlaisista puutteista, ei se missään nimessä osoita epäonnistumista. Tarkoituksena on vain nostaa esiin asioita joita minä tulkitsen haasteiksi, joita ei vielä tähän mennessä ole ratkaistu.

### Rekisteröinti
Rekisteröinti ei onnistu, sillä `csrf_token` -arvoa yritetään lukea istunnosta, ennen kuin sitä on sinne kirjoitettu.
https://github.com/jmakine/Koe-sovellus/blob/ad32afd2a61146069478f393068b0251ff3b301f/routes.py#L34-L38

KeyError syntyy täällä:
https://github.com/jmakine/Koe-sovellus/blob/ad32afd2a61146069478f393068b0251ff3b301f/users.py#L98-L99
Positiivista on, että sovellus noudattaa tältä osin fail-secure tai fail-closed periaatetta, onnistuneesti välttäen heikkeuden [CWE-636: Not Failing Securely ('Failing Open')](https://cwe.mitre.org/data/definitions/636.html)

Väliaikaisesti poistin CSRF-tarkistuksen rekisteröinnistä, jotta pääsin tekemään ensimmäisen käyttäjän.

Tästä eteenpäin CSRF-tarkistus hieman hämmentävästi onnistuukin samalla sivulla, kun tekee lisää käyttäjiä. Johtunee siitä, että logoutissa `csrf_session` -arvoa ei poisteta istunnosta. Sen vuoksi tätä on varmaankin ollut vaikea havaita testeissä.

### Virheenkäsittely
Tämä on enimmäkseen piilossa oleva asia, joka ei välttämättä koskaan aiheuta ongelmia, mutta saattaa aiheuttaa vaikeasti selvitettäviä ongelmia joskus myöhemmin.

Esimerkkinä, jos koetta lisätessä valitsee aikarajaksi jonkun poskettoman suuren luvun (yli 2147483647), tietokantaan lisäys epäonnistuu (toteuttaen heikkouden [CWE-1284: Improper Validation of Specified Quantity in Input](https://cwe.mitre.org/data/definitions/1284.html)), kun se ei mahdu integer-tyyppiseen sarakkeeseen. Se ei itsessään ole suurikaan ongelma, mutta virhe kuoletetaan sen syntypaikassa, ilman että syntyy lokimerkintää tai ilmoitusta käyttäjälle.
https://github.com/jmakine/Koe-sovellus/blob/ad32afd2a61146069478f393068b0251ff3b301f/exams.py#L23-L30
Kutsuva funktio puolestaan jättää paluuarvon kokonaan tarkistamatta, aiheuttaen heikkouden [CWE-252: Unchecked Return Value](https://cwe.mitre.org/data/definitions/252.html).
https://github.com/jmakine/Koe-sovellus/blob/ad32afd2a61146069478f393068b0251ff3b301f/routes.py#L211-L212

Sama toimintamalli on systemaattisesti käytössä monessa muussakin funktiossa.

### Pääsynhallinta
Osassa reiteistä ei ole pääsynhallintaa, esim:
Kirjautumaton käyttäjä näkee kokeet, kun veikkaa id-numeron:
https://github.com/jmakine/Koe-sovellus/blob/ad32afd2a61146069478f393068b0251ff3b301f/routes.py#L165-L166
Kirjautumaton käyttäjä aiheuttaa käsittelemättömän virheen, joka johtaa error 500:
https://github.com/jmakine/Koe-sovellus/blob/ad32afd2a61146069478f393068b0251ff3b301f/routes.py#L227-L228

### Luottamusongelma
Rivillä 83 luetaan muuttujaan tieto, joka on peräisin asiakkaalta. Myöhemmin rivillä 90, muuttujaa käytetään ohjaamaan koodin haarautumista.

https://github.com/jmakine/Koe-sovellus/blob/ad32afd2a61146069478f393068b0251ff3b301f/routes.py#L81-L91

Tieto on peräisin seuraavista piilotetuista kentistä.
https://github.com/jmakine/Koe-sovellus/blob/ad32afd2a61146069478f393068b0251ff3b301f/templates/index.html#L13-L15
https://github.com/jmakine/Koe-sovellus/blob/ad32afd2a61146069478f393068b0251ff3b301f/templates/users.html#L43-L45

Luottamalla koodin haarautuminen sen varaan että käyttäjä ei muokkaa piilotettua kenttää, tullaan aiheuttaneeksi heikkous [CWE-472: External Control of Assumed-Immutable Web Parameter](https://cwe.mitre.org/data/definitions/472.html). Käytännössä on siis mahdollista poistaa viimeinen opettaja, vaikka sen ei kuuluisi olla mahdollista.

## Yhteenveto
Hienoa työtä! Sovellus alkaa olemaan hyvin paketissa, viilausta vaille valmis, kuten oli tavoitteena 👍
Vastaan mielelläni jos palautteesta jäi jotain kysyttävää.

**Comment by jmakine** [comment]
Kiitos arvokkaasta palautteesta! Erittäin valideja pointteja, jotka livahtaneet oman tutkan ohi täysin. :) 
Uskon korjanneeni nämä, mutta pidän silmät auki ja tsekkailen jos jotain jäänyt vielä fiksailematta.
